In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sklearn as skl
warnings.filterwarnings('ignore')
%matplotlib inline
#UST2is the cleanup data, the smaller one

In [40]:
DF = pd.read_csv("Columbia_edited.csv")

In [41]:
DF.head()

id  member_id    CLI        term  int_rate  installment grade  \
0  1077501    1296599   5000   36 months     10.65       162.87     B   
1  1077430    1314167   2500   60 months     15.27        59.83     C   
2  1077175    1313524   2400   36 months     15.96        84.33     C   
3  1076863    1277178  10000   36 months     13.49       339.31     C   
4  1075358    1311748   3000   60 months     12.69        67.79     B   

  sub_grade emp_length home_ownership         ...          out_prncp_inv  \
0        B2  10+ years           RENT         ...                    0.0   
1        C4   < 1 year           RENT         ...                    0.0   
2        C5  10+ years           RENT         ...                    0.0   
3        C1  10+ years           RENT         ...                    0.0   
4        B5     1 year           RENT         ...                  766.9   

    total_pymnt total_pymnt_inv  total_rec_prncp  total_rec_int  \
0   5861.071414         5831.78          5000.00         861.07   
1   1008.710000         1008.71           456.46         435.17   
2   3003.653644         3003.65          2400.00         603.65   
3  12226.302210        12226.30         10000.00        2209.33   
4   3242.170000         3242.17          2233.10        1009.07   

   total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt  \
0                0.00        0.00                     0.00           171.62   
1                0.00      117.08                     1.11           119.66   
2                0.00        0.00                     0.00           649.91   
3               16.97        0.00                     0.00           357.48   
4                0.00        0.00                     0.00            67.79   

   last_credit_pull_d  
0              16-Jan  
1              13-Sep  
2              16-Jan  
3              15-Jan  
4              16-Jan  

[5 rows x 32 columns]

In [42]:
DF.shape

(100, 32)

In [43]:
DF.describe()

id     member_id           CLI    int_rate  installment  \
count  1.000000e+02  1.000000e+02    100.000000  100.000000    100.00000   
mean   1.066996e+06  1.298888e+06   9986.500000   13.020400    302.90740   
std    7.784985e+03  1.053401e+04   5380.282722    3.956175    163.47233   
min    1.032111e+06  1.261745e+06   1000.000000    6.030000     35.31000   
25%    1.068484e+06  1.298932e+06   6000.000000   10.650000    168.27750   
50%    1.069072e+06  1.303455e+06  10000.000000   12.690000    296.20500   
75%    1.069544e+06  1.304264e+06  12425.000000   15.960000    404.72500   
max    1.077501e+06  1.314167e+06  31825.000000   22.060000    995.82000   

          annual_inc         dti  delinq_2yrs  inq_last_6mths    open_acc  \
count     100.000000  100.000000   100.000000      100.000000  100.000000   
mean    57573.441900   14.305500     0.080000        0.970000    8.820000   
std     26999.818922    6.469216     0.393893        1.086696    3.610814   
min     12252.000000    1.000000     0.000000        0.000000    2.000000   
25%     40000.000000    9.807500     0.000000        0.000000    6.000000   
50%     50000.000000   14.000000     0.000000        1.000000    8.000000   
75%     75000.000000   20.002500     0.000000        2.000000   11.000000   
max    150000.000000   29.440000     3.000000        5.000000   20.000000   

            ...           out_prncp  out_prncp_inv   total_pymnt  \
count       ...          100.000000     100.000000    100.000000   
mean        ...          209.006600     208.662600  10686.111311   
std         ...          784.158403     782.760261   6743.046963   
min         ...            0.000000       0.000000      0.000000   
25%         ...            0.000000       0.000000   5438.655000   
50%         ...            0.000000       0.000000  10381.755000   
75%         ...            0.000000       0.000000  14079.839592   
max         ...         4523.910000    4516.510000  34886.080000   

       total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
count       100.000000       100.000000     100.000000          100.000000   
mean      10656.307200      8597.749200    2008.884300            0.959103   
std        6678.262668      5623.218357    1927.725399            4.259756   
min           0.000000         0.000000       0.000000            0.000000   
25%        5438.655000      4393.750000     694.675000            0.000000   
50%       10381.755000      8350.000000    1440.650000            0.000000   
75%       14079.840000     12000.000000    2432.712500            0.000000   
max       34886.080000     31825.000000    9519.710000           24.170000   

        recoveries  collection_recovery_fee  last_pymnt_amnt  
count   100.000000               100.000000       100.000000  
mean     78.518300                 8.457263      2595.705300  
std     371.625842                64.271577      3948.083744  
min       0.000000                 0.000000         0.000000  
25%       0.000000                 0.000000       216.947500  
50%       0.000000                 0.000000       422.375000  
75%       0.000000                 0.000000      4018.437500  
max    3486.000000               625.617000     16966.700000  

[8 rows x 24 columns]

In [44]:
from sklearn.model_selection import train_test_split #for split the data
from sklearn.metrics import accuracy_score  #for accuracy_score
from sklearn.model_selection import KFold #for K-fold cross validation
from sklearn.model_selection import cross_val_score #score evaluation
from sklearn.model_selection import cross_val_predict #prediction
from sklearn.model_selection import GridSearchCV # for Hyper parameter tuning
from sklearn.metrics import confusion_matrix #for confusion matrix
from sklearn import metrics

In [56]:
#I dropped the earliest_cr_line and last_credit_pull_d.
#*******************************************************
#*******************************************************

In [57]:
all_features = DF.drop("grade",axis=1)
Targeted_feature = DF["grade"]

# total of 6891 records in dataset
# Divide the data set into two- 70% for train and 30% for test

#X_train,X_test,y_train,y_test = train_test_split(all_features,Targeted_feature,test_size=0.3)  
X_train,X_test,y_train,y_test = train_test_split(all_features,Targeted_feature,test_size=0.3,random_state=42) 

# Check the train test data set shape
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((70, 30), (30, 30), (70,), (30,))

In [58]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label = LabelEncoder()
loan_status = ["Charged Off", "Current", "Fully Paid"]

int_data = label.fit_transform(loan_status)
int_data = int_data.reshape(len(int_data), 1)

onehot_data = OneHotEncoder(sparse=False)
onehot_data = onehot_data.fit_transform(int_data)
print("Categorical data encoded into integer values....\n")
print(onehot_data)

Categorical data encoded into integer values....

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

ModuleNotFoundError: No module named 'sklearn.compose'

In [59]:
# Train the logistic regression model with training data

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

ValueError: could not convert string to float: 'Fully Paid'